POST http://localhost:8080/api/auth/local/register
Content-Type: application/json

{
    "username": "penpitcha123",
    "email": "s6602041520161@gmail.kmutnb.ac.th",
    "password": "Penpitcha150345"
}