POST http://localhost:8080/api/students
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM2Nzc0NTQ4LCJleHAiOjE3MzkzNjY1NDh9.d1v0Bk3PCZ6EnLygNBRNTfb19i1bXxOYCwGi03W_rkw
//Student  1=> Your name
# {
#   "data": {
#     "name": "Penpitcha Prayonghom",
#     "mobile": "0985267029",
#     "cardId": "1169800238597"
#   }
# }
//Student 2 => Your Friend

{
"data": {
"name": "Chonlatharn Nambut",
"mobile": "0839274565",
"cardId": "6602041520047"
}
}
