POST http://localhost:8080/api/subjects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM2Nzc0NTQ4LCJleHAiOjE3MzkzNjY1NDh9.d1v0Bk3PCZ6EnLygNBRNTfb19i1bXxOYCwGi03W_rkw

{
  "data": {
    "name": "Cyber Security"
  }
}